ALTER TABLE IF EXISTS "instructor" ADD COLUMN IF NOT EXISTS "facebook_link" TEXT;
ALTER TABLE IF EXISTS "instructor" ADD COLUMN IF NOT EXISTS "twitter_link" TEXT;
ALTER TABLE IF EXISTS "instructor" ADD COLUMN IF NOT EXISTS "linkedin_link" TEXT;
ALTER TABLE IF EXISTS "instructor" ADD COLUMN IF NOT EXISTS "instagram_link" TEXT;
ALTER TABLE IF EXISTS "instructor" ADD COLUMN IF NOT EXISTS "website_link" TEXT;

ALTER TABLE IF EXISTS "person" ADD COLUMN IF NOT EXISTS "facebook_link" TEXT;
ALTER TABLE IF EXISTS "person" ADD COLUMN IF NOT EXISTS "twitter_link" TEXT;
ALTER TABLE IF EXISTS "person" ADD COLUMN IF NOT EXISTS "linkedin_link" TEXT;
ALTER TABLE IF EXISTS "person" ADD COLUMN IF NOT EXISTS "instagram_link" TEXT;
ALTER TABLE IF EXISTS "person" ADD COLUMN IF NOT EXISTS "website_link" TEXT;
