name: Git Repo Keep-Alive

on:
  schedule:
    - cron: "0 0 1 * *" # Every 1st day of the month at 00:00
  workflow_dispatch:

jobs:
  keep-alive:
    name: Prevent GitHub Actions Inactivity
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Keep-Alive Workflow
        uses: gautamkrishnar/keepalive-workflow@v2
        with:
          commit_message: "chore: repository keep-alive"
